name: GitHub Actions Demo
on:
  workflow_dispatch:
    branches: [cd-check]
jobs:
  Continuous_Integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: echo "Workflow started"
    - name: Workflow Dispatch
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: .github\workflows\workflow1.yml
        token: ${{ secrets.ACCESS_TOKEN }}
        inputs: '{"message": "blah blah"}'
    - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Install dependencies
      run: npm install
    - name: Build 
      run: npm run build
    - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - run: echo "ğŸ This job's status is ${{ job.status }}."
